# Config file .travis.yml

sudo: required
language: python

python:
  - "2.7"

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow

before_install:
  - git clone https://github.com/OCA/account-invoicing $HOME/account-invoicing -b 7.0
  - git clone https://github.com/OCA/account-financial-tools $HOME/account-financial-tools -b 7.0
  - git clone https://github.com/OCA/webkit-tools $HOME/webkit-tools -b 7.0
  - git clone https://github.com/OCA/account-payment $HOME/account-payment -b 7.0

env:
  - VERSION="7.0" TESTS="1" LINT_CHECK="1" TRANSIFEX="0" ODOO_REPO="odoo/odoo"
  - VERSION="7.0" TESTS="1" LINT_CHECK="1" TRANSIFEX="0" ODOO_REPO="OCA/OCB"
 

virtualenv:
  system_site_packages: true


install:
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
#  - sudo pip install python-ldap raven raven_sanitize_openerp bzr GitPython
#  - printf '[options]\n\nrunning_env = dev' > ${HOME}/.openerp_serverrc
#  - pip install coveralls


script:
  - travis_run_tests


after_success:
#  coveralls
